import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from 'react-hot-toast'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-2 space-y-2`}
      >
        {children}
        <Toaster position="top-center" toastOptions={{
          success:{duration:2000,style:{background:'green',color:'white'}},
          error:{duration:3000, style:{background: 'red', color:'white'}}
        }}/>
      </body>
    </html>
  );
}
